window.CCAT_ANSWERS = {
  1: { answer: "B", explanation: "The sequence stays with four-sided figures; the parallelogram continues that visual family." },
  2: { answer: "E", explanation: "0.02 is smaller than 0.2, 0.5301, 1.305, and 3.15." },
  3: { answer: "B", explanation: "175 increased by 20% is 175 x 1.2 = 210." },
  4: { answer: "D", explanation: "The filled slanted block alternates lean direction; the next one leans the same way as option D." },
  5: { answer: "D", explanation: "The block pattern rotates through the sequence; option D matches the next rotation." },
  6: { answer: "A", explanation: "The sequence alternates straight-edged and curved shapes; the next straight-edged four-sided figure is A." },
  7: { answer: "B", explanation: "The internal lines and shaded sector rotate consistently; option B is the next rotation." },
  8: { answer: "B", explanation: "A salmon is a type of fish; oxygen is a type of element." },
  9: { answer: "C", explanation: "A canoe is a type of boat; a helicopter is a type of aircraft." },
  10: { answer: "D", explanation: "Occupied and vacant are opposites; honorable and shameful are also opposites." },
  11: { answer: "B", explanation: "Amiability means friendliness, which explains a blossoming social life and many friends." },
  12: { answer: "E", explanation: "A stirring statement can inspire more than a generic platitude." },
  13: { answer: "C", explanation: "A propensity is a tendency; unhealthy eating means he should restrict calories." },
  14: { answer: "B", explanation: "Exacerbated means made worse, which explains the patient returning to the hospital." },
  15: { answer: "C", explanation: "C is the only figure where the innermost shape is not a small square." },
  16: { answer: "D", explanation: "D is the odd one out: it is a half-dome form, unlike the others that are circular pieces with a cutout." },
  17: { answer: "C", explanation: "C is the odd one out because the inner and outer shapes repeat in a way the others do not." },
  18: { answer: "A", explanation: "A uses only three repeated symbols; the others use a different mixed-symbol structure." },
  19: { answer: "E", explanation: "A $25 hat at 40% off costs $15. $105 / $15 = 7." },
  20: { answer: "C", explanation: "If 7 is 25%, then the whole is 7 / 0.25 = 28." },
  21: { answer: "D", explanation: "The series moves aceg, bdfh, cegi, dfhj, so the next group is egik." },
  22: { answer: "C", explanation: "Wearing a uniform does not prove Jeff works in electronics; the conclusion is uncertain." },
  23: { answer: "A", explanation: "Knowing someone is not transitive, so Abby may know Denise and Denise may know Sonny while Abby does not." },
  24: { answer: "B", explanation: "If all supporters voted and Victoria did not vote, then Victoria was not a supporter." },
  25: { answer: "D", explanation: "Four company names match exactly between the two columns." },
  26: { answer: "B", explanation: "Only two entries match exactly between the two company-name columns." },
  27: { answer: "A", explanation: "Only one address matches exactly: 9 W Third St." },
  28: { answer: "C", explanation: "Rows increase from two to three to four shapes; the missing cell is three outlined triangles." },
  29: { answer: "C", explanation: "The symbols rotate position through the grid; option C has the required arrangement." },
  30: { answer: "A", explanation: "The middle cell should contain a small filled diamond lower-left and outlined diamond upper-right." },
  31: { answer: "A", explanation: "The sequence multiplies to reach 27, then 27 x 3 = 81." },
  32: { answer: "C", explanation: "3.5 ounces per latte times 200 lattes equals 700 ounces." },
  33: { answer: "B", explanation: "56 / 1.4 = 40 and 56 / 1.6 = 35, for 75 total root canals." },
  34: { answer: "A", explanation: "Malign means speak badly of; diplomatic means tactful." },
  35: { answer: "D", explanation: "Unkempt means messy." },
  36: { answer: "B", explanation: "The price rose from $0.75 to $0.90; $0.15 / $0.75 = 20%." },
  37: { answer: "C", explanation: "Four numbers averaging 18 sum to 72. 12 + 24 + 16 = 52, so the last number is 20." },
  38: { answer: "", explanation: "Question image 38 is missing from the folder." },
  39: { answer: "D", explanation: "If 40% were born after 2000, then 60% were not. 0.6 x 0.6 = 36%." },
  40: { answer: "A", explanation: "Dejection is the opposite of elation." },
  41: { answer: "D", explanation: "Proven is the opposite of rumored." },
  42: { answer: "B", explanation: "A framework provides support; a hobby provides amusement." },
  43: { answer: "C", explanation: "Reckless lacks caution; mean lacks compassion." },
  44: { answer: "A", explanation: "Condense means shorten; accessible means easier for the audience to understand." },
  45: { answer: "E", explanation: "Let x be $5 plates and 2x be $10 plates: 5x + 20x = 900, so x = 36 and total plates = 108." },
  46: { answer: "A", explanation: "After dropouts, 8 women and 12 men remain; 8 / 20 = 40%." },
  47: { answer: "D", explanation: "(1 + 4 + 8 + 17 + 32) / 5 = 62 / 5 = 12.4." },
  48: { answer: "C", explanation: "8 brands x 6 flavors x 3 sizes = 144 combinations." },
  49: { answer: "D", explanation: "0.4 women + 0.6 men = 0.52 overall implies men are 60% of voters." },
  50: { answer: "E", explanation: "Alice has the frog, Luke got his pet in 2012, and the cat was first, so Jenny got the cat in 2010." }
};
