window.CCAT_SETS = [
  {
    id: "ccat",
    title: "CCAT 2",
    sourcePath: "CCAT-2",
    questions: [
      { id: "ccat-01", number: 1, type: "image", prompt: "Question 1", image: "question-01.jpg", answer: "B", explanation: "The sequence stays with four-sided figures; the parallelogram continues that visual family." },
      { id: "ccat-02", number: 2, type: "image", prompt: "Question 2", image: "question-02.jpg", answer: "E", explanation: "0.02 is smaller than 0.2, 0.5301, 1.305, and 3.15." },
      { id: "ccat-03", number: 3, type: "image", prompt: "Question 3", image: "question-03.jpg", answer: "B", explanation: "175 increased by 20% is 175 x 1.2 = 210." },
      { id: "ccat-04", number: 4, type: "image", prompt: "Question 4", image: "question-04.jpg", answer: "D", explanation: "The filled slanted block alternates lean direction; the next one leans the same way as option D." },
      { id: "ccat-05", number: 5, type: "image", prompt: "Question 5", image: "question-05.jpg", answer: "D", explanation: "The block pattern rotates through the sequence; option D matches the next rotation." },
      { id: "ccat-06", number: 6, type: "image", prompt: "Question 6", image: "question-06.jpg", answer: "A", explanation: "The sequence alternates straight-edged and curved shapes; the next straight-edged four-sided figure is A." },
      { id: "ccat-07", number: 7, type: "image", prompt: "Question 7", image: "question-07.jpg", answer: "B", explanation: "The internal lines and shaded sector rotate consistently; option B is the next rotation." },
      { id: "ccat-08", number: 8, type: "image", prompt: "Question 8", image: "question-08.jpg", answer: "B", explanation: "A salmon is a type of fish; oxygen is a type of element." },
      { id: "ccat-09", number: 9, type: "image", prompt: "Question 9", image: "question-09.jpg", answer: "C", explanation: "A canoe is a type of boat; a helicopter is a type of aircraft." },
      { id: "ccat-10", number: 10, type: "image", prompt: "Question 10", image: "question-10.jpg", answer: "D", explanation: "Occupied and vacant are opposites; honorable and shameful are also opposites." },
      { id: "ccat-11", number: 11, type: "image", prompt: "Question 11", image: "question-11.jpg", answer: "B", explanation: "Amiability means friendliness, which explains a blossoming social life and many friends." },
      { id: "ccat-12", number: 12, type: "image", prompt: "Question 12", image: "question-12.jpg", answer: "E", explanation: "A stirring statement can inspire more than a generic platitude." },
      { id: "ccat-13", number: 13, type: "image", prompt: "Question 13", image: "question-13.jpg", answer: "C", explanation: "A propensity is a tendency; unhealthy eating means he should restrict calories." },
      { id: "ccat-14", number: 14, type: "image", prompt: "Question 14", image: "question-14.jpg", answer: "B", explanation: "Exacerbated means made worse, which explains the patient returning to the hospital." },
      { id: "ccat-15", number: 15, type: "image", prompt: "Question 15", image: "question-15.jpg", answer: "C", explanation: "C is the only figure where the innermost shape is not a small square." },
      { id: "ccat-16", number: 16, type: "image", prompt: "Question 16", image: "question-16.jpg", answer: "D", explanation: "D is the odd one out: it is a half-dome form, unlike the others that are circular pieces with a cutout." },
      { id: "ccat-17", number: 17, type: "image", prompt: "Question 17", image: "question-17.jpg", answer: "C", explanation: "C is the odd one out because the inner and outer shapes repeat in a way the others do not." },
      { id: "ccat-18", number: 18, type: "image", prompt: "Question 18", image: "question-18.jpg", answer: "A", explanation: "A uses only three repeated symbols; the others use a different mixed-symbol structure." },
      { id: "ccat-19", number: 19, type: "image", prompt: "Question 19", image: "question-19.jpg", answer: "E", explanation: "A $25 hat at 40% off costs $15. $105 / $15 = 7." },
      { id: "ccat-20", number: 20, type: "image", prompt: "Question 20", image: "question-20.jpg", answer: "C", explanation: "If 7 is 25%, then the whole is 7 / 0.25 = 28." },
      { id: "ccat-21", number: 21, type: "image", prompt: "Question 21", image: "question-21.jpg", answer: "D", explanation: "The series moves aceg, bdfh, cegi, dfhj, so the next group is egik." },
      { id: "ccat-22", number: 22, type: "image", prompt: "Question 22", image: "question-22.jpg", answer: "C", explanation: "Wearing a uniform does not prove Jeff works in electronics; the conclusion is uncertain." },
      { id: "ccat-23", number: 23, type: "image", prompt: "Question 23", image: "question-23.jpg", answer: "A", explanation: "Knowing someone is not transitive, so Abby may know Denise and Denise may know Sonny while Abby does not." },
      { id: "ccat-24", number: 24, type: "image", prompt: "Question 24", image: "question-24.jpg", answer: "B", explanation: "If all supporters voted and Victoria did not vote, then Victoria was not a supporter." },
      { id: "ccat-25", number: 25, type: "image", prompt: "Question 25", image: "question-25.jpg", answer: "D", explanation: "Four company names match exactly between the two columns." },
      { id: "ccat-26", number: 26, type: "image", prompt: "Question 26", image: "question-26.jpg", answer: "B", explanation: "Only two entries match exactly between the two company-name columns." },
      { id: "ccat-27", number: 27, type: "image", prompt: "Question 27", image: "question-27.jpg", answer: "A", explanation: "Only one address matches exactly: 9 W Third St." },
      { id: "ccat-28", number: 28, type: "image", prompt: "Question 28", image: "question-28.jpg", answer: "C", explanation: "Rows increase from two to three to four shapes; the missing cell is three outlined triangles." },
      { id: "ccat-29", number: 29, type: "image", prompt: "Question 29", image: "question-29.jpg", answer: "C", explanation: "The symbols rotate position through the grid; option C has the required arrangement." },
      { id: "ccat-30", number: 30, type: "image", prompt: "Question 30", image: "question-30.jpg", answer: "A", explanation: "The middle cell should contain a small filled diamond lower-left and outlined diamond upper-right." },
      { id: "ccat-31", number: 31, type: "image", prompt: "Question 31", image: "question-31.jpg", answer: "A", explanation: "The sequence multiplies to reach 27, then 27 x 3 = 81." },
      { id: "ccat-32", number: 32, type: "image", prompt: "Question 32", image: "question-32.jpg", answer: "C", explanation: "3.5 ounces per latte times 200 lattes equals 700 ounces." },
      { id: "ccat-33", number: 33, type: "image", prompt: "Question 33", image: "question-33.jpg", answer: "B", explanation: "56 / 1.4 = 40 and 56 / 1.6 = 35, for 75 total root canals." },
      { id: "ccat-34", number: 34, type: "image", prompt: "Question 34", image: "question-34.jpg", answer: "A", explanation: "Malign means speak badly of; diplomatic means tactful." },
      { id: "ccat-35", number: 35, type: "image", prompt: "Question 35", image: "question-35.jpg", answer: "D", explanation: "Unkempt means messy." },
      { id: "ccat-36", number: 36, type: "image", prompt: "Question 36", image: "question-36.jpg", answer: "B", explanation: "The price rose from $0.75 to $0.90; $0.15 / $0.75 = 20%." },
      { id: "ccat-37", number: 37, type: "image", prompt: "Question 37", image: "question-37.jpg", answer: "C", explanation: "Four numbers averaging 18 sum to 72. 12 + 24 + 16 = 52, so the last number is 20." },
      { id: "ccat-38", number: 38, type: "image", prompt: "Question 38", image: "question-38.jpg", explanation: "Question image 38 is missing from the folder.", missing: true },
      { id: "ccat-39", number: 39, type: "image", prompt: "Question 39", image: "question-39.jpg", answer: "D", explanation: "If 40% were born after 2000, then 60% were not. 0.6 x 0.6 = 36%." },
      { id: "ccat-40", number: 40, type: "image", prompt: "Question 40", image: "question-40.jpg", answer: "A", explanation: "Dejection is the opposite of elation." },
      { id: "ccat-41", number: 41, type: "image", prompt: "Question 41", image: "question-41.jpg", answer: "D", explanation: "Proven is the opposite of rumored." },
      { id: "ccat-42", number: 42, type: "image", prompt: "Question 42", image: "question-42.jpg", answer: "B", explanation: "A framework provides support; a hobby provides amusement." },
      { id: "ccat-43", number: 43, type: "image", prompt: "Question 43", image: "question-43.jpg", answer: "C", explanation: "Reckless lacks caution; mean lacks compassion." },
      { id: "ccat-44", number: 44, type: "image", prompt: "Question 44", image: "question-44.jpg", answer: "A", explanation: "Condense means shorten; accessible means easier for the audience to understand." },
      { id: "ccat-45", number: 45, type: "image", prompt: "Question 45", image: "question-45.jpg", answer: "E", explanation: "Let x be $5 plates and 2x be $10 plates: 5x + 20x = 900, so x = 36 and total plates = 108." },
      { id: "ccat-46", number: 46, type: "image", prompt: "Question 46", image: "question-46.jpg", answer: "A", explanation: "After dropouts, 8 women and 12 men remain; 8 / 20 = 40%." },
      { id: "ccat-47", number: 47, type: "image", prompt: "Question 47", image: "question-47.jpg", answer: "D", explanation: "(1 + 4 + 8 + 17 + 32) / 5 = 62 / 5 = 12.4." },
      { id: "ccat-48", number: 48, type: "image", prompt: "Question 48", image: "question-48.jpg", answer: "C", explanation: "8 brands x 6 flavors x 3 sizes = 144 combinations." },
      { id: "ccat-49", number: 49, type: "image", prompt: "Question 49", image: "question-49.jpg", answer: "D", explanation: "0.4 women + 0.6 men = 0.52 overall implies men are 60% of voters." },
      { id: "ccat-50", number: 50, type: "image", prompt: "Question 50", image: "question-50.jpg", answer: "E", explanation: "Alice has the frog, Luke got his pet in 2012, and the cat was first, so Jenny got the cat in 2010." }
    ]
  },
  {
    id: "ccat-1",
    title: "CCAT 1",
    sourcePath: "CCAT-1",
    questions: [
      { id: "ccat-1-01", number: 1, type: "image", prompt: "Question 1", image: "1.jpeg", explanation: "16 per hour * 7 hours = 112.", answer: "C" },
      { id: "ccat-1-02", number: 2, type: "image", prompt: "Question 2", image: "2.jpeg", explanation: "Compare decimals; 0.146 is smallest.", answer: "A" },
      { id: "ccat-1-03", number: 3, type: "image", prompt: "Question 3", image: "3.jpeg", explanation: "1200 * 1.15 = 1380.", answer: "D" },
      { id: "ccat-1-04", number: 4, type: "image", prompt: "Question 4", image: "4.jpeg", answer: "B", explanation: "Pattern alternates vertical and horizontal filled bowties; next is vertical filled." },
      { id: "ccat-1-05", number: 5, type: "image", prompt: "Question 5", image: "5.jpeg", answer: "C", explanation: "Shape pattern keeps the same block layout with shifted filled squares." },
      { id: "ccat-1-06", number: 6, type: "image", prompt: "Question 6", image: "6.jpeg", answer: "B", explanation: "Sequence alternates curved and straight shapes; next should be curved oval." },
      { id: "ccat-1-07", number: 7, type: "image", prompt: "Question 7", image: "7.jpeg", answer: "A", explanation: "Shaded sector rotates around the circle; next is upper-right." },
      { id: "ccat-1-08", number: 8, type: "image", prompt: "Question 8", image: "8.jpeg", explanation: "Pencil is used to write; oven is used to bake." },
      { id: "ccat-1-09", number: 9, type: "image", prompt: "Question 9", image: "9.jpeg", explanation: "Canoe is a type of boat; helicopter is a type of aircraft.", answer: "C" },
      { id: "ccat-1-10", number: 10, type: "image", prompt: "Question 10", image: "10.jpeg", explanation: "Occupied and vacant are opposites; honorable and shameful are opposites.", answer: "D" },
      { id: "ccat-1-11", number: 11, type: "image", prompt: "Question 11", image: "11.jpeg", explanation: "Mentor guidance is tutelage.", answer: "E" },
      { id: "ccat-1-12", number: 12, type: "image", prompt: "Question 12", image: "12.jpeg", explanation: "Contrast: performance was good, but firing was still inevitable.", answer: "D" },
      { id: "ccat-1-13", number: 13, type: "image", prompt: "Question 13", image: "13.jpeg", explanation: "Poor grades contrasted with previously excellent performance.", answer: "C" },
      { id: "ccat-1-14", number: 14, type: "image", prompt: "Question 14", image: "14.jpeg", explanation: "Lawsuits gave rumors more attention, so they amplified them." },
      { id: "ccat-1-15", number: 15, type: "image", prompt: "Question 15", image: "15.jpeg", answer: "D", explanation: "D is the only one with a square center instead of a diamond center." },
      { id: "ccat-1-16", number: 16, type: "image", prompt: "Question 16", image: "16.jpeg", answer: "B", explanation: "D uniquely swaps the inner/middle circle-square order." },
      { id: "ccat-1-17", number: 17, type: "image", prompt: "Question 17", image: "17.jpeg", answer: "D", explanation: "C is the only one with an inner circle rather than an inner diamond." },
      { id: "ccat-1-18", number: 18, type: "image", prompt: "Question 18", image: "18.jpeg", answer: "E", explanation: "In A-D, bottom row reverses top row; E does not." },
      { id: "ccat-1-19", number: 19, type: "image", prompt: "Question 19", image: "19.jpeg", explanation: "20% off $10 gives $8; $64 / $8 = 8.", answer: "B" },
      { id: "ccat-1-20", number: 20, type: "image", prompt: "Question 20", image: "20.jpeg", explanation: "7 is 20% of 35.", answer: "B" },
      { id: "ccat-1-21", number: 21, type: "image", prompt: "Question 21", image: "21.jpeg", explanation: "Letters move m,l,k,j -> i; s,r,q,p -> o; d,e,f,g -> h." },
      { id: "ccat-1-22", number: 22, type: "image", prompt: "Question 22", image: "22.jpeg", explanation: "Jeff works in the store; all store workers wear uniforms.", answer: "A" },
      { id: "ccat-1-23", number: 23, type: "image", prompt: "Question 23", image: "23.jpeg", explanation: "Knowing Denise does not prove whether Abby knows Sonny.", answer: "C" },
      { id: "ccat-1-24", number: 24, type: "image", prompt: "Question 24", image: "24.jpeg", explanation: "Attending the concert does not prove orchestra membership.", answer: "C" },
      { id: "ccat-1-25", number: 25, type: "image", prompt: "Question 25", image: "25.jpeg", explanation: "All five company names match exactly.", answer: "E" },
      { id: "ccat-1-26", number: 26, type: "image", prompt: "Question 26", image: "26.jpeg", explanation: "Harrell Automotive and Two Ferns Realty match; others differ.", answer: "B" },
      { id: "ccat-1-27", number: 27, type: "image", prompt: "Question 27", image: "27.jpeg", explanation: "McIntyre, Sycamore, and Causeway entries match exactly." },
      { id: "ccat-1-28", number: 28, type: "image", prompt: "Question 28", image: "28.jpeg", answer: "B", explanation: "Matrix uses shape by column and count/fill by row; missing is three filled circles." },
      { id: "ccat-1-29", number: 29, type: "image", prompt: "Question 29", image: "29.jpeg", answer: "B", explanation: "Top row uses three-sided shapes; missing top-middle is another triangle." },
      { id: "ccat-1-30", number: 30, type: "image", prompt: "Question 30", image: "30.jpeg", answer: "C", explanation: "Center cell follows the same positional rotation as matching symbol groups." },
      { id: "ccat-1-31", number: 31, type: "image", prompt: "Question 31", image: "31.jpeg", explanation: "1, 3, 9, 27 multiply by 3; next is 81.", answer: "A" },
      { id: "ccat-1-32", number: 32, type: "image", prompt: "Question 32", image: "32.jpeg", explanation: "1.20 MB * 140 extractions = 168 MB.", answer: "D" },
      { id: "ccat-1-33", number: 33, type: "image", prompt: "Question 33", image: "33.jpeg", explanation: "56/3.5 = 16 and 56/4 = 14; total 30.", answer: "A" },
      { id: "ccat-1-34", number: 34, type: "image", prompt: "Question 34", image: "34.jpeg", explanation: "Slow rollout made effectiveness hard to measure; problems appeared later.", answer: "E" },
      { id: "ccat-1-35", number: 35, type: "image", prompt: "Question 35", image: "35.jpeg", explanation: "He promised to keep the car clean.", answer: "C" },
      { id: "ccat-1-36", number: 36, type: "image", prompt: "Question 36", image: "36.jpeg", explanation: "In 1962 Maris hit 33 vs Mantle 30; 3/30 = 10%.", answer: "C" },
      { id: "ccat-1-37", number: 37, type: "image", prompt: "Question 37", image: "37.jpeg", explanation: "Four numbers average 13, total 52; 52 - (10+17+5) = 20.", answer: "E" },
      { id: "ccat-1-38", number: 38, type: "image", prompt: "Question 38", image: "38.jpeg", explanation: "15 * 1.5 * 1.1 = 24.75." },
      { id: "ccat-1-39", number: 39, type: "image", prompt: "Question 39", image: "39.jpeg", explanation: "5% * 5% = 0.25%.", answer: "A" },
      { id: "ccat-1-40", number: 40, type: "image", prompt: "Question 40", image: "40.jpeg", explanation: "Germane means relevant, opposite of irrelevant.", answer: "C" },
      { id: "ccat-1-41", number: 41, type: "image", prompt: "Question 41", image: "41.jpeg", explanation: "Rumored means unverified; proven is verified.", answer: "D" },
      { id: "ccat-1-42", number: 42, type: "image", prompt: "Question 42", image: "42.jpeg", explanation: "Fallible people can make mistakes; gullible people can be misled.", answer: "A" },
      { id: "ccat-1-43", number: 43, type: "image", prompt: "Question 43", image: "43.jpeg", explanation: "Fond relates to affection; aberrant relates to anomaly." },
      { id: "ccat-1-44", number: 44, type: "image", prompt: "Question 44", image: "44.jpeg", explanation: "Both describe arrogant rude treatment of service staff.", answer: "E" },
      { id: "ccat-1-45", number: 45, type: "image", prompt: "Question 45", image: "45.jpeg", explanation: "Average between 15 and 17 means sum between 60 and 68; only 61 fits." },
      { id: "ccat-1-46", number: 46, type: "image", prompt: "Question 46", image: "46.jpeg", explanation: "Team A has 12 left; Team B has 8; 12/20 = 60%.", answer: "B" },
      { id: "ccat-1-47", number: 47, type: "image", prompt: "Question 47", image: "47.jpeg", explanation: "Jacob is 80% of 35 = 28; grandmother is 3 * 28 = 84.", answer: "B" },
      { id: "ccat-1-48", number: 48, type: "image", prompt: "Question 48", image: "48.jpeg", explanation: "36 total, 4 neither, so 32 in either; 29 + 11 - 32 = 8." },
      { id: "ccat-1-49", number: 49, type: "image", prompt: "Question 49", image: "49.jpeg", explanation: "After 30% drop, value is 70%; 30/70 = 42.9% gain needed.", answer: "C" },
      { id: "ccat-1-50", number: 50, type: "image", prompt: "Question 50", image: "50.jpeg", explanation: "Monthly values average to 1040 from the chart.", answer: "B" }
    ]
  },
  {
    id: "ccat-3",
    title: "CCAT 3",
    sourcePath: "CCAT-3",
    questions: [
      { id: "ccat-3-09", number: 9, type: "image", prompt: "Question 9", image: "09.JPG" },
      { id: "ccat-3-10", number: 10, type: "image", prompt: "Question 10", image: "10.JPG" },
      { id: "ccat-3-11", number: 11, type: "image", prompt: "Question 11", image: "11.JPG" },
      { id: "ccat-3-12", number: 12, type: "image", prompt: "Question 12", image: "12.JPG" },
      { id: "ccat-3-13", number: 13, type: "image", prompt: "Question 13", image: "13.JPG" },
      { id: "ccat-3-14", number: 14, type: "image", prompt: "Question 14", image: "14.JPG" },
      { id: "ccat-3-15", number: 15, type: "image", prompt: "Question 15", image: "15.JPG" },
      { id: "ccat-3-16", number: 16, type: "image", prompt: "Question 16", image: "16.JPG" },
      { id: "ccat-3-17", number: 17, type: "image", prompt: "Question 17", image: "17.JPG" },
      { id: "ccat-3-18", number: 18, type: "image", prompt: "Question 18", image: "18.JPG" },
      { id: "ccat-3-19", number: 19, type: "image", prompt: "Question 19", image: "19.JPG" },
      { id: "ccat-3-20", number: 20, type: "image", prompt: "Question 20", image: "20.JPG" },
      { id: "ccat-3-21", number: 21, type: "image", prompt: "Question 21", image: "21.JPG" },
      { id: "ccat-3-22", number: 22, type: "image", prompt: "Question 22", image: "22.JPG" },
      { id: "ccat-3-23", number: 23, type: "image", prompt: "Question 23", image: "23.JPG" },
      { id: "ccat-3-24", number: 24, type: "image", prompt: "Question 24", image: "24.JPG" },
      { id: "ccat-3-25", number: 25, type: "image", prompt: "Question 25", image: "25.JPG" },
      { id: "ccat-3-26", number: 26, type: "image", prompt: "Question 26", image: "26.JPG" },
      { id: "ccat-3-27", number: 27, type: "image", prompt: "Question 27", image: "27.JPG" },
      { id: "ccat-3-28", number: 28, type: "image", prompt: "Question 28", image: "28.JPG" },
      { id: "ccat-3-29", number: 29, type: "image", prompt: "Question 29", image: "29.JPG" },
      { id: "ccat-3-30", number: 30, type: "image", prompt: "Question 30", image: "30.JPG" },
      { id: "ccat-3-31", number: 31, type: "image", prompt: "Question 31", image: "31.JPG" },
      { id: "ccat-3-32", number: 32, type: "image", prompt: "Question 32", image: "32.JPG" },
      { id: "ccat-3-33", number: 33, type: "image", prompt: "Question 33", image: "33.JPG" },
      { id: "ccat-3-34", number: 34, type: "image", prompt: "Question 34", image: "34.JPG" },
      { id: "ccat-3-35", number: 35, type: "image", prompt: "Question 35", image: "35.JPG" },
      { id: "ccat-3-36", number: 36, type: "image", prompt: "Question 36", image: "36.JPG" },
      { id: "ccat-3-37", number: 37, type: "image", prompt: "Question 37", image: "37.JPG" },
      { id: "ccat-3-38", number: 38, type: "image", prompt: "Question 38", image: "38.JPG" },
      { id: "ccat-3-39", number: 39, type: "image", prompt: "Question 39", image: "39.JPG" },
      { id: "ccat-3-40", number: 40, type: "image", prompt: "Question 40", image: "40.JPG" },
      { id: "ccat-3-41", number: 41, type: "image", prompt: "Question 41", image: "41.JPG" },
      { id: "ccat-3-42", number: 42, type: "image", prompt: "Question 42", image: "42.JPG" },
      { id: "ccat-3-43", number: 43, type: "image", prompt: "Question 43", image: "43.JPG" },
      { id: "ccat-3-44", number: 44, type: "image", prompt: "Question 44", image: "44.JPG" },
      { id: "ccat-3-45", number: 45, type: "image", prompt: "Question 45", image: "45.JPG" },
      { id: "ccat-3-46", number: 46, type: "image", prompt: "Question 46", image: "46.JPG" },
      { id: "ccat-3-47", number: 47, type: "image", prompt: "Question 47", image: "47.JPG" },
      { id: "ccat-3-48", number: 48, type: "image", prompt: "Question 48", image: "48.JPG" },
      { id: "ccat-3-49", number: 49, type: "image", prompt: "Question 49", image: "49.JPG" },
      { id: "ccat-3-50", number: 50, type: "image", prompt: "Question 50", image: "50.JPG" }
    ]
  },
  {
    id: "ccat-4",
    title: "CCAT 4 PDF",
    sourcePath: "CCAT-4",
    questions: [
      { id: "ccat-4-01", number: 1, category: "Math", type: "text", prompt: "If a factory produces 16 lawn mowers per hour, how many lawn mowers can it produce in seven hours?", choices: { A: "96", B: "105", C: "112", D: "120", E: "128" }, answer: "C", explanation: "16 x 7 = 112." },
      { id: "ccat-4-02", number: 2, category: "Math", type: "text", prompt: "Which of the following is the smallest value?", choices: { A: "0.146", B: "2.0102", C: "0.45", D: "1.09", E: "2.001" }, answer: "A", explanation: "0.146 is the smallest." },
      { id: "ccat-4-03", number: 3, category: "Math", type: "text", prompt: "In one month, a farm produces 1200 pounds of potatoes. In the following month, the amount of potatoes it produces increases by 15% over the previous month. How many potatoes does it produce in the second month?", choices: { A: "1280 pounds", B: "1320 pounds", C: "1350 pounds", D: "1380 pounds", E: "1450 pounds" }, answer: "D", explanation: "1200 x 1.15 = 1380." },
      { id: "ccat-4-04", number: 4, category: "Spatial", type: "image", prompt: "Which of the following boxes should replace the question mark (?) to complete the pattern?", image: "question-000.png", choices: { A: "A", B: "B", C: "C", D: "D", E: "E" }, answer: "B", explanation: "Spatial item from PDF. Official key: B." },
      { id: "ccat-4-05", number: 5, category: "Spatial", type: "image", prompt: "Which of the following boxes should replace the question mark (?) to complete the pattern?", image: "question-001.png", choices: { A: "A", B: "B", C: "C", D: "D", E: "E" }, answer: "C", explanation: "Spatial item from PDF. Official key: C." },
      { id: "ccat-4-06", number: 6, category: "Spatial", type: "image", prompt: "Which of the following boxes should replace the question mark (?) to complete the pattern?", image: "question-002.png", choices: { A: "A", B: "B", C: "C", D: "D", E: "E" }, answer: "B", explanation: "Spatial item from PDF. Official key: B." },
      { id: "ccat-4-07", number: 7, category: "Spatial", type: "image", prompt: "Which of the following boxes should replace the question mark (?) to complete the pattern?", image: "question-003.png", choices: { A: "A", B: "B", C: "C", D: "D", E: "E" }, answer: "A", explanation: "Spatial item from PDF. Official key: A." },
      { id: "ccat-4-09", number: 9, category: "Verbal", type: "text", prompt: "CANOE is to BOAT as ...", choices: { A: "MAST is to SAIL", B: "SUBMARINE is to OCEAN", C: "HELICOPTER is to AIRCRAFT", D: "OAR is to MOTOR", E: "PILOT is to CREW" }, answer: "C", explanation: "A canoe is a type of boat; a helicopter is a type of aircraft." },
      { id: "ccat-4-10", number: 10, category: "Verbal", type: "text", prompt: "OCCUPIED is to VACANT as ...", choices: { A: "BEAUTIFUL is to SIGHT", B: "BLISSFUL is to HAPPINESS", C: "CONSERVED is to RETAINED", D: "HONORABLE is to SHAMEFUL", E: "MYOPIC is to SHORTSIGHTED" }, answer: "D", explanation: "Both pairs are antonyms." },
      { id: "ccat-4-11", number: 11, category: "Verbal", type: "text", prompt: "Under her mentor's ______, guided by the mentor's decades of experience, the new employee quickly developed the skills that she needed to excel in her job.", choices: { A: "pilferage", B: "suffrage", C: "shortage", D: "umbrage", E: "tutelage" }, answer: "E", explanation: "Tutelage means guidance or instruction." },
      { id: "ccat-4-12", number: 12, category: "Verbal", type: "text", prompt: "Even though the team's performance ______ under their old manager, his firing was inevitable given his unethical actions behind closed doors.", choices: { A: "stalled", B: "dwindled", C: "tarnished", D: "flourished", E: "meandered" }, answer: "D", explanation: "Even though signals contrast; performance was good despite the firing." },
      { id: "ccat-4-13", number: 13, category: "Verbal", type: "text", prompt: "The father ______ his son for his poor grades, which contrasted with the son's ______ academic performance in the previous semester.", choices: { A: "berated .. lackluster", B: "overlooked .. fervent", C: "rebuked .. superlative", D: "superseded .. impeccable", E: "chastised .. mediocre" }, answer: "C", explanation: "Poor grades contrast with excellent prior performance." },
      { id: "ccat-4-15", number: 15, category: "Spatial", type: "image", prompt: "Which of the following does not belong?", image: "question-004.png", choices: { A: "A", B: "B", C: "C", D: "D", E: "E" }, answer: "D", explanation: "Spatial item from PDF. Official key: D." },
      { id: "ccat-4-16", number: 16, category: "Spatial", type: "image", prompt: "Which of the following does not belong?", image: "question-005.png", choices: { A: "A", B: "B", C: "C", D: "D", E: "E" }, answer: "B", explanation: "Spatial item from PDF. Official key: B." },
      { id: "ccat-4-17", number: 17, category: "Spatial", type: "image", prompt: "Which of the following does not belong?", image: "question-006.png", choices: { A: "A", B: "B", C: "C", D: "D", E: "E" }, answer: "D", explanation: "Spatial item from PDF. Official key: D." },
      { id: "ccat-4-18", number: 18, category: "Spatial", type: "image", prompt: "Which of the following does not belong?", image: "question-007.png", choices: { A: "A", B: "B", C: "C", D: "D", E: "E" }, answer: "E", explanation: "Spatial item from PDF. Official key: E." },
      { id: "ccat-4-19", number: 19, category: "Math", type: "text", prompt: "A restaurant has a special where all appetizers are sold at a discount of 20%. If the regular price of an appetizer is $10, how many appetizers could be bought at the discount price if a customer spent $64?", choices: { A: "6", B: "8", C: "10", D: "12", E: "14" }, answer: "B", explanation: "$10 at 20% off is $8. $64 / $8 = 8." },
      { id: "ccat-4-20", number: 20, category: "Math", type: "text", prompt: "7 is 20% of what number?", choices: { A: "32", B: "35", C: "38", D: "42", E: "49" }, answer: "B", explanation: "7 / 0.20 = 35." },
      { id: "ccat-4-22", number: 22, category: "Logic", type: "text", prompt: "Assume the first two statements are true. Is the final statement: 1) True, 2) False, or 3) Uncertain based on the information provided?\n\nJeff works in the electronics store.\nPeople who work in the electronics store wear uniforms.\nJeff wears a uniform.", choices: { A: "True", B: "False", C: "Uncertain" }, answer: "A", explanation: "Store employees wear uniforms; Jeff works there." },
      { id: "ccat-4-23", number: 23, category: "Logic", type: "text", prompt: "Assume the first two statements are true. Is the final statement: 1) True, 2) False, or 3) Uncertain based on the information provided?\n\nAbby knows Denise.\nDenise knows Sonny.\nAbby does not know Sonny.", choices: { A: "True", B: "False", C: "Uncertain" }, answer: "C", explanation: "The premises do not establish whether Abby knows Sonny." },
      { id: "ccat-4-24", number: 24, category: "Logic", type: "text", prompt: "Assume the first two statements are true. Is the final statement: 1) True, 2) False, or 3) Uncertain based on the information provided?\n\nAll members of the orchestra attended the concert.\nLisa attended the concert.\nLisa was a member of the orchestra.", choices: { A: "True", B: "False", C: "Uncertain" }, answer: "C", explanation: "Non-members could also have attended." },
      { id: "ccat-4-25", number: 25, category: "Verbal", type: "text", prompt: "How many of the five items in the left hand column are exactly the same as the corresponding entry in the right hand column?\n\n1. Mendelson Industries | Mendelson Industries\n2. Hernandez Pharmaceuticals | Hernandez Pharmaceuticals\n3. Jenkins Architectural Design | Jenkins Architectural Design\n4. Holmes Banking and Loans | Holmes Banking and Loans\n5. Wheeler Lawn Services | Wheeler Lawn Services", choices: { A: "1", B: "2", C: "3", D: "4", E: "5" }, answer: "E", explanation: "All five entries match exactly." },
      { id: "ccat-4-26", number: 26, category: "Verbal", type: "text", prompt: "How many of the five items in the left hand column are exactly the same as the corresponding entry in the right hand column?\n\n1. Middleton Training Inc. | Middletown Training Inc.\n2. Laurelmont Corp. | Laurelmont Co.\n3. Harrell Automotive | Harrell Automotive\n4. Two Ferns Realty | Two Ferns Realty\n5. Simpson Hardware | Stimpson Hardware", choices: { A: "1", B: "2", C: "3", D: "4", E: "5" }, answer: "B", explanation: "Rows 3 and 4 match exactly." },
      { id: "ccat-4-28", number: 28, category: "Spatial", type: "image", prompt: "Which of the following boxes should replace the question mark (?) to complete the pattern?", image: "question-008.png", choices: { A: "A", B: "B", C: "C", D: "D", E: "E" }, answer: "B", explanation: "Spatial item from PDF. Official key: B." },
      { id: "ccat-4-29", number: 29, category: "Spatial", type: "image", prompt: "Which of the following boxes should replace the question mark (?) to complete the pattern?", image: "question-009.png", choices: { A: "A", B: "B", C: "C", D: "D", E: "E" }, answer: "B", explanation: "Spatial item from PDF. Official key: B." },
      { id: "ccat-4-30", number: 30, category: "Spatial", type: "image", prompt: "Which of the following boxes should replace the question mark (?) to complete the pattern?", image: "question-010.png", choices: { A: "A", B: "B", C: "C", D: "D", E: "E" }, answer: "C", explanation: "Spatial item from PDF. Official key: C." },
      { id: "ccat-4-31", number: 31, category: "Math", type: "text", prompt: "What would be the next number in the following series?\n\n1 ... 3 ... 9 ... 27 ... ?", choices: { A: "81", B: "122", C: "162", D: "203", E: "243" }, answer: "A", explanation: "Each term is multiplied by 3." },
      { id: "ccat-4-32", number: 32, category: "Math", type: "text", prompt: "A data analyst uses 1.25 megabytes of storage on her computer for each data extraction performed. If she performs 140 data extractions per month, how many megabytes of storage will she need each month?", choices: { A: "168", B: "170", C: "174", D: "175", E: "181" }, answer: "D", explanation: "1.25 x 140 = 175." },
      { id: "ccat-4-33", number: 33, category: "Math", type: "text", prompt: "An electrician can complete a repair in 3.5 hours. His less experienced colleague takes 4.0 hours to complete a repair. If both individuals start working at the same time, and each works 56 hours over the course of one week, how many total repairs will they have completed?", choices: { A: "30", B: "32", C: "34", D: "36", E: "38" }, answer: "A", explanation: "56 / 3.5 = 16 and 56 / 4 = 14, total 30." },
      { id: "ccat-4-34", number: 34, category: "Verbal", type: "text", prompt: "Because of the company's decision to roll out the new marketing strategy slowly, it was difficult to ______ its effectiveness, and the ______ of the new approach were not clear until almost a year later, when sales began to suffer.", choices: { A: "gauge ... metrics", B: "conceptualize ... results", C: "monitor ... virtues", D: "determine ... advantages", E: "measure ... limitations" }, answer: "E", explanation: "Sales suffering points to limitations." },
      { id: "ccat-4-35", number: 35, category: "Verbal", type: "text", prompt: "His new car was already a mess even though he had promised himself he would keep his car ______.", choices: { A: "intrepid", B: "precise", C: "immaculate", D: "unkempt", E: "dexterous" }, answer: "C", explanation: "Immaculate means perfectly clean." },
      { id: "ccat-4-36", number: 36, category: "Math", type: "image", prompt: "The bar chart below shows the number of home runs hit by Mickey Mantle and Roger Maris when they played together on the Yankees between 1960 and 1964. Expressed as a percentage, how many more home runs did Maris hit in 1962 relative to Mantle's 1962 total?", image: "question-011.png", choices: { A: "3%", B: "9%", C: "10%", D: "17%", E: "20%" }, answer: "C", explanation: "Maris 33 and Mantle 30 gives 3 / 30 = 10%." },
      { id: "ccat-4-37", number: 37, category: "Math", type: "text", prompt: "A group of four numbers has an average (arithmetic mean) of 13. The first three numbers are 10, 17, and 5. What is the other number?", choices: { A: "13", B: "15", C: "17", D: "18", E: "20" }, answer: "E", explanation: "4 x 13 = 52. 52 - 32 = 20." },
      { id: "ccat-4-39", number: 39, category: "Math", type: "text", prompt: "An estimated 5% of all people have hazel eyes. If two people are selected at random from around the world, what are the chances that BOTH of these people have hazel eyes?", choices: { A: "0.25%", B: "1.00%", C: "2.50%", D: "10.00%", E: "25.00%" }, answer: "A", explanation: "0.05 x 0.05 = 0.0025 = 0.25%." },
      { id: "ccat-4-40", number: 40, category: "Verbal", type: "text", prompt: "Choose the word that is most nearly OPPOSITE to the word in capital letters.\n\nIRRELEVANT", choices: { A: "supercilious", B: "prevalent", C: "germane", D: "progressive", E: "extraneous" }, answer: "C", explanation: "Germane means relevant." },
      { id: "ccat-4-41", number: 41, category: "Verbal", type: "text", prompt: "Choose the word that is most nearly OPPOSITE to the word in capital letters.\n\nRUMORED", choices: { A: "supposed", B: "potential", C: "bullied", D: "proven", E: "doubtful" }, answer: "D", explanation: "Rumored means unverified; proven means established as fact." },
      { id: "ccat-4-42", number: 42, category: "Verbal", type: "text", prompt: "FALLIBLE is to MISTAKE as ...", choices: { A: "GULLIBLE is to MISLEAD", B: "RATIONAL is to REASON", C: "LEGIBLE is to WRITING", D: "CREDIBLE is to DELAY", E: "FUNGIBLE is to DISTRACT" }, answer: "A", explanation: "Fallible is prone to mistake; gullible is prone to being misled." },
      { id: "ccat-4-44", number: 44, category: "Verbal", type: "text", prompt: "Based on the ______ behavior and ______ toward service staff exhibited by the job applicant before his interview, the hiring manager decided not to move forward with his application.", choices: { A: "gregarious .. conceit", B: "atrocious .. pity", C: "obnoxious .. chivalry", D: "ambitious .. disdain", E: "supercilious .. insolence" }, answer: "E", explanation: "Both words are negative and fit poor treatment of staff." },
      { id: "ccat-4-46", number: 46, category: "Math", type: "text", prompt: "A company hires 14 new employees onto Sales Team A and 14 new employees onto Sales Team B. Within one year, 2 of the new Team A employees and 6 of the new Team B employees have quit. What percentage of the remaining employees are on Team A?", choices: { A: "55%", B: "60%", C: "65%", D: "70%", E: "75%" }, answer: "B", explanation: "Team A has 12 left, total remaining is 20, and 12 / 20 = 60%." },
      { id: "ccat-4-47", number: 47, category: "Math", type: "text", prompt: "Jacob is one third the age of his grandmother, and 20% younger than his sister. If Jacob's sister is 35 years old, how old is Jacob's grandmother?", choices: { A: "82", B: "84", C: "86", D: "88", E: "90" }, answer: "B", explanation: "Jacob is 35 x 0.80 = 28. Grandmother is 28 x 3 = 84." },
      { id: "ccat-4-49", number: 49, category: "Math", type: "text", prompt: "An investor buys stock in a company and in the twelve months after she invests the value of the stock decreases by 30%. By what amount will the value of the stock need to go up from there in order that the price of the stock will be equal to what the investor first paid for it?", choices: { A: "30%", B: "37.5%", C: "42.9%", D: "45%", E: "46.7%" }, answer: "C", explanation: "From 70 back to 100 requires 30 / 70 = 42.9%." },
      { id: "ccat-4-50", number: 50, category: "Math", type: "image", prompt: "The graph below shows the number of books a book store sold per month. What is the average number of books sold per month during the five month period?", image: "question-012.png", choices: { A: "1220", B: "1040", C: "890", D: "1170", E: "920" }, answer: "B", explanation: "The answer key selects the closest answer, 1040." }
    ]
  }
];
